# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otherix < Formula
  desc "Otherix operator CLI."
  homepage "https://github.com/otherix/otherix"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/otherix/otherix/releases/download/v0.2.0/otherix_0.2.0_darwin_amd64.tar.gz"
      sha256 "cf0b9b24ef9283db62ab03a5cabbbb8bc6151b77baf3e9418ae4821908107d54"

      define_method(:install) do
        bin.install "otherix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/otherix/otherix/releases/download/v0.2.0/otherix_0.2.0_darwin_arm64.tar.gz"
      sha256 "29bfe9ecba9f6363a5573ac783dce357522ebb6a42b5bd659aa5e55b59f50f25"

      define_method(:install) do
        bin.install "otherix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otherix/otherix/releases/download/v0.2.0/otherix_0.2.0_linux_amd64.tar.gz"
      sha256 "7cb6b2b2b43cdc620145b3ca8e9f795a2266e7a1a277778248ef2830676032dc"
      define_method(:install) do
        bin.install "otherix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otherix/otherix/releases/download/v0.2.0/otherix_0.2.0_linux_arm64.tar.gz"
      sha256 "1103b52a9581c9726827ef46a19b53c499dc67972b0bb34aafe8aa5d27e5c572"
      define_method(:install) do
        bin.install "otherix"
      end
    end
  end
end
