# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtherixSsh < Formula
  desc "Otherix external SSH connector for granted VMs."
  homepage "https://github.com/otherix/otherix"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/otherix/otherix/releases/download/v0.3.1/otherix-ssh_0.3.1_darwin_amd64.tar.gz"
      sha256 "63c23e0ebe24566e95755c3cc540e9d35405ad365f723db92ed057aec9c7b919"

      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/otherix/otherix/releases/download/v0.3.1/otherix-ssh_0.3.1_darwin_arm64.tar.gz"
      sha256 "3cb221088f4fe996ec66a636a5f4adcdfbdee432c627658d9b3831153194f8b7"

      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otherix/otherix/releases/download/v0.3.1/otherix-ssh_0.3.1_linux_amd64.tar.gz"
      sha256 "962e8fe059b4218aa6465fb4f22eb8b996f2e14d0093b1b05c257f49beb8626a"
      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otherix/otherix/releases/download/v0.3.1/otherix-ssh_0.3.1_linux_arm64.tar.gz"
      sha256 "437ed8cba50f93fcdaaa30161e0b007efc4e21b327ecc166a469d22d93928bf9"
      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
  end
end
