# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtherixSsh < Formula
  desc "Otherix external SSH connector for granted VMs."
  homepage "https://github.com/otherix/otherix"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/otherix/otherix/releases/download/v0.3.0/otherix-ssh_0.3.0_darwin_amd64.tar.gz"
      sha256 "04c608870913585d79356537deeb7b6a50df619a2d5e1eaa26322254fc005893"

      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/otherix/otherix/releases/download/v0.3.0/otherix-ssh_0.3.0_darwin_arm64.tar.gz"
      sha256 "867a833cfc8ed023f70baa85d7c213864b8ff8be05e62265d845f783b2a130d8"

      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otherix/otherix/releases/download/v0.3.0/otherix-ssh_0.3.0_linux_amd64.tar.gz"
      sha256 "ebe110b74b7522b0a727ee9ac624b1ea02b777624de67bd4697bb5bf6dd391d4"
      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otherix/otherix/releases/download/v0.3.0/otherix-ssh_0.3.0_linux_arm64.tar.gz"
      sha256 "31e4db6c95ff9012794d528b4dbefebedc14cade6c1b498bcc59d3976c49163f"
      define_method(:install) do
        bin.install "otherix-ssh"
      end
    end
  end
end
